-- Generated by HyprMod

-- Environment
hl.env("XCURSOR_THEME", "ArcStarry-cursors")
hl.env("XCURSOR_SIZE", "24")

-- Settings
hl.config({
    general = {
        col = {
            active_border = {
                colors = {"rgba(adc6ffff)", "rgba(99c1f1ff)"},
                angle = 90,
            },
        },
        gaps_in = 4,
        gaps_out = 13,
    },
    input = {
        accel_profile = "flat",
        kb_layout = "gb,br",
        kb_options = "grp:alt_shift_toggle,caps:escape_shifted_capslock",
        kb_variant = "",
        numlock_by_default = true,
    },
})

-- Monitors
hl.monitor({
    output = "DP-1",
    disabled = false,
    mode = "3440x1440@74.98Hz",
    position = "0x0",
    scale = 1,
    cm = "srgb",
})
